

GET http://localhost:5000/api/teams/user
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQyMzY5ZDk2MGJmMzMwNjZmYmViNGIxIn0sImlhdCI6MTU2MjYxNjA3NiwiZXhwIjoxNTYyOTc2MDc2fQ.PbhmH1qEf0HnTb-7AMBY5FuT13a8vaJmA0t0-DuKUCc
